### ISSUE TITLE
Why these urls are not working??

### ISSUE THREAD

**Issue by fulldump** [hblend/hblend#14]
``` css
@font-face {
    font-family: 'FontAwesome';
    src: url('[[path https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/fonts/fontawesome-webfont.eot?v=4.5.0]]');
    src: url('[[path https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/fonts/fontawesome-webfont.eot?#iefix&v=4.5.0]]') format('embedded-opentype'),
         url('[[path https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/fonts/fontawesome-webfont.woff2?v=4.5.0]]') format('woff2'),
         url('[[path https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/fonts/fontawesome-webfont.woff?v=4.5.0]]') format('woff'),
         url('[[path https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/fonts/fontawesome-webfont.ttf?v=4.5.0]]') format('truetype'),
         url('[[path https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/fonts/fontawesome-webfont.svg?v=4.5.0#fontawesomeregular]]') format('svg');
    font-weight: normal;
    font-style: normal;
}
```
